// Test generated by RoostGPT for test nodeJsTest1 using AI Type Azure Open AI and AI Model roost-gpt4-32k

import { addVariable } from "./postmanCollectionProcessor";

describe("Testing addVariable function", () => {
  let variablesSet;

  beforeEach(() => {
    variablesSet = new Set();
  });

  test("should add the given variable to the set", () => {
    addVariable("variable1");
    expect(variablesSet.has("variable1")).toBeTruthy();
  });

  test("should not add duplicate variable to the set", () => {
    variablesSet.add("variable1");
    addVariable("variable1");
    expect(variablesSet.size).toBe(1);
  });

  test("should throw an error if the variable is not provided", () => {
    expect(() => addVariable()).toThrow("Variable is required");
  });

  test("should throw an error if the variable is not a string", () => {
    expect(() => addVariable(123)).toThrow("Variable must be a string");
  });
});
