// Test generated by RoostGPT for test nodeJsTest1 using AI Type Azure Open AI and AI Model roost-gpt4-32k

import { addVariable } from "./postmanCollectionProcessor.js";

describe("addVariable function", () => {
  
  let variablesSet;

  beforeEach(() => {
    variablesSet = new Set();
  });

  test("it should add variable to the set", () => {
    const variable = "newVariable";
    addVariable(variable);
    expect(variablesSet.has(variable)).toBe(true);
  });

  test("it should not add duplicate variable to the set", () => {
    const variable = "duplicateVariable";
    addVariable(variable);
    addVariable(variable);
    expect(variablesSet.size).toBe(1);
  });

  test("it should handle null variable", () => {
    const variable = null;
    addVariable(variable);
    expect(variablesSet.has(variable)).toBe(false);
  });

  test("it should handle undefined variable", () => {
    const variable = undefined;
    addVariable(variable);
    expect(variablesSet.has(variable)).toBe(false);
  });

});
