// Test generated by RoostGPT for test nodeJsTest1 using AI Type Azure Open AI and AI Model roost-gpt4-32k

import { addVariable } from './postmanCollectionProcessor';

describe('PostmanCollectionProcessor', () => {
  let variablesSet;

  beforeEach(() => {
    variablesSet = new Set();
  });

  test('should add variable to the set', () => {
    const variable = 'testVariable';

    addVariable(variable);

    expect(variablesSet.has(variable)).toBeTruthy();
  });

  test('should not add same variable twice to the set', () => {
    const variable = 'testVariable';

    addVariable(variable);
    addVariable(variable);

    expect(variablesSet.size).toBe(1);
  });

  test('should handle empty variable', () => {
    const variable = '';

    addVariable(variable);

    expect(variablesSet.has(variable)).toBeFalsy();
  });

  test('should handle undefined variable', () => {
    const variable = undefined;

    addVariable(variable);

    expect(variablesSet.has(variable)).toBeFalsy();
  });
});
