// Test generated by RoostGPT for test nodeJsTest1 using AI Type Azure Open AI and AI Model roost-gpt4-32k

import { processNode } from "./postmanCollectionProcessor.js";

describe('processNode function', () => {
    let mockItem;
    let mockAddVariable;

    beforeEach(() => {
        mockItem = {
            key: 'testKey',
            value: 'testValue'
        };

        mockAddVariable = jest.fn()

        global.exemptHeaders = [];
        global.addVariable = mockAddVariable;
    });

    it('converts object property into postman variables while leaving exempt headers intact', async () => {
        expect(await processNode(mockItem)).toEqual({
            key: 'testKey',
            value: '{{testKey}}'
        });
        expect(mockAddVariable).toHaveBeenCalledWith('{{testKey}}');
    });

    it('does not convert exempt headers into postman variables', async () => {
        global.exemptHeaders = ['testKey'];
        expect(await processNode(mockItem)).toEqual({
            key: 'testKey',
            value: 'testValue'
        });
        expect(mockAddVariable).not.toHaveBeenCalledWith('{{testKey}}');
    });

    it('returns the same value if not an object or array', async () => {
        const testValue = "testValue";
        expect(await processNode(testValue)).toBe(testValue);
    });
  
    it('handles null values correctly', async () => {
        expect(await processNode(null)).toBeNull();
    });
});
